name: Prettier

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Check formatting
        run: pnpm prettier --format:check
      - name: Check linting
        run: pnpm run lint --max-warnings=0
